### PR TITLE
Fix Linux compatibility and add French translation

### PR DESCRIPTION
**Pull request by mouahrara**
* (9558d2cb58b3d0aea6ae264260b2ed341ec81144) Renamed the `building` directory to ensure Linux compatibility
* (73b286785c48deea1d9449ae2024e6db9a2de7d2) Added French translation

### CODE REVIEW

**Comment by Molenfeuer** [comment]
Ouhh.. So the folder name **is** case sensitive! I will merge your changes into the upcoming 1.4 release!

For my notes: Which Linux distribution do you use?

**Comment by mouahrara** [comment]
I use Arch Linux, but it should be the same for all Linux distributions.

**Comment by Molenfeuer** [comment]
@RandomWolf I think @Floogen / PeacefulEnd use hardcoded filepaths for including my assets! You might not know that the foldername "Buildings" is not set by me. Instead its forced by [Solid Foundations](https://github.com/Floogen/SolidFoundations#solid-foundations) itself!

Kuss und Gruß
Leon

**Comment by Molenfeuer** [comment]
@mouahrara Can you also test the Linux compatibility of [Millnificent Collab (AT and SF)](https://www.nexusmods.com/stardewvalley/mods/16931)?

**Comment by mouahrara** [comment]
@RandomWolf On Linux, the file system (ext4) is case-sensitive, meaning that it treats `Buildings` and `buildings` as separate entities. On the other hand, the Windows file system (NTFS) is case-insensitive, meaning that it treats `Buildings` and `buildings` as the same. As a result, when Solid Foundations tries to access the `Buildings` folder, Linux won't find it, whereas the `buildings` folder is found on Windows.
You can easily check this by trying to create two folders `Buildings` and `buildings` in the same directory. Linux will create both folders, but Windows won't create the second one because a folder with the same name already exists.

**Comment by mouahrara** [comment]
@Molenfeuer I tested, and the problem is the same with the `textures` directory, which must be renamed to `Textures`.

**Comment by Molenfeuer** [comment]
Mehhh. I accidentally merged your request into [main](https://github.com/Molenfeuer/Millnificent/tree/main) :/ So, I undid the merge, but I can't reopen your pull request :< So... can you create this request again :D?

**Comment by mouahrara** [comment]
Done.

**Pull request merged**
